[package]
name = "oxc_formatter"
version = "0.1.0"
edition = "2024"

[dependencies]
oxc_allocator = "0.55.0"
oxc_ast = "0.55.0"
oxc_parser = "0.55.0"
oxc_span = "0.55.0"

rustc-hash = "2.1.1"
drop_bomb = "0.1.5"
unicode-width = "0.1.12"

